# This file contains all of the dependencies to setup the dualrnaseq pipeline
# It can also be used to setup an environment to replicate the pipeline (for testing, local analysis etc)
# To do this, use the following command: conda env create -f environment.yml
name: nf-core-dualrnaseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::fastqc=0.11.9
  - bioconda::samtools=1.9
  - bioconda::salmon=1.3.0
  - bioconda::STAR=2.7.3a
  - bioconda::gffread=0.12.1
  - bioconda::multiqc=1.8
  - bioconda::htseq=0.12.4
  - bioconda::bbmap=38.87
  - bioconda::cutadapt=3.2
  - bioconda::pysam=0.15.3
  - bioconda::bioconductor-rtracklayer=1.48.0
  - bioconda::bioconductor-tximport=1.16.0
  - conda-forge::python=3.7.6
  - conda-forge::r-plyr=1.8.6
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::numpy=1.19.5
  - conda-forge::pandas=1.1.5
  - conda-forge::biopython=1.78
  - conda-forge::seaborn=0.10.0
  - conda-forge::matplotlib=3.1.1
