contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dualrnaseq channel"
    url: https://nfcore.slack.com/channels/dualrnaseq
    about: Discussion about the nf-core/dualrnaseq pipeline
